version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: db-record-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      # 挂载外部配置文件目录
      - ./config:/app/config:ro
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - db-record-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: db-record-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - db-record-network

networks:
  db-record-network:
    driver: bridge